#!/bin/sh
# Copyright © 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

host_fwd() {
    local fwd_rules=
    for v in $(echo $1|cut -d, -f1- --output-delimiter=' '); do
        fwd_rules=$fwd_rules,hostfwd=tcp::${v%%:*}-:${v##*:}
    done
    echo $fwd_rules
}

CMD="qemu-kvm -nographic                                                                    \
    -name process=aconvm-$(shuf -i 100000-1000000 -n1)                                        \
    -accel kvm                                                                              \
    ${TD:+-object tdx-guest,id=tdx -object memory-backend-memfd-private,id=ram1,size=2g}    \
    -machine q35${TD:+,memory-backend=ram1,kernel_irqchip=split,confidential-guest-support=tdx} \
    -cpu host,-kvm-steal-time,pmu=off                                                       \
    -smp ${ACON_STARTVM_PARAM_VP_NUM:-4}                                                     \
    -m ${ACON_STARTVM_PARAM_MEM:-2g}                                                         \
    -nodefaults -vga none -no-hpet                                                          \
    -nic user,model=virtio,ipv6=off,ipv4=on,hostname=${TD:+td-}${TD:-vm}$(host_fwd $ACON_STARTVM_PARAM_TCPFWD) \
    ${CID:+-device vhost-vsock-pci,guest-cid=$(test $CID -gt 2 && echo $CID || echo $$)}    \
    -bios $(dirname $0)/OVMF.fd                                                             \
    -chardev stdio,id=mux,mux=on,signal=off                                                 \
    -device virtio-serial,max_ports=1 -device virtconsole,chardev=mux                       \
    -serial chardev:mux                                                                     \
    -monitor chardev:mux                                                                    \
    -append \"ip=dhcp console=hvc0 earlyprintk=ttyS0 ${CID:+acond.vsock_conn} $ACON_STARTVM_PARAM_KA\"      \
    -initrd ${ACON_STARTVM_PARAM_RAMDISK:-$(dirname $0)/initrd.img}                                             \
    -kernel \"${ACON_STARTVM_PARAM_KERNEL:-$(dirname $0)/kernel.img}\""

echo $CMD

eval exec $CMD
