name: CICD-BusyBox

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'

env:
  CARGO_TERM_COLOR: always

permissions:
  actions: read
  checks: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  CICD:

    runs-on: self-hosted
    name: CICD-BusyBox
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: Enable busybox docker
      run: |
        source scripts/start-happypath.sh
        run_workload -d test -i acon_busybox -f bundle.dockerfile -j '.uids+=[2] | .writableFS=true' -o invoke
