name: CICD-Nginx

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - 'doc/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  CICD:

    runs-on: self-hosted
    name: CICD-Nginx
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Enable Nginx docker
      run: |
        source scripts/start-happypath.sh
        run_workload -d test -i acon_nginx -f nginx.dockerfile -j '.uids+=[101] | .writableFS=true | .entrypoint+=["nginx", "-g", "daemon off;"]'
