name: CICD-MySQL

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - 'doc/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  CICD:

    runs-on: self-hosted
    name: CICD-MySQL
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Enable MySQL docker
      run: |
        source scripts/start-happypath.sh
        ATD_MEMSZ=8g run_workload -d test -i mysql -j '.writableFS=true | .uids+=[999] | .entrypoint+=["mysqld"] | .env+=["MYSQL_ROOT_PASSWORD=my-secret-pw"]'
