name: Debian Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: Debian Builds
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Debian builds
      shell: docker build --progress=plain -t acond -f {0} .
      run: |
        FROM rust:slim
        RUN apt update -y && \
          apt upgrade -y && \
          apt install -y pkg-config libssl-dev git musl-tools protobuf-compiler libprotobuf-dev
        COPY . ACON
        RUN cd ACON/acond && \
          CARGO_BUILD_RUSTFLAGS=-Ctarget-feature=-crt-static cargo build --release
