name: Debian Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare Dockerfile
      shell: cp {0} Dockerfile
      run: |
        FROM rust:slim
        RUN apt update -y && \
          apt upgrade -y && \
          apt install -y pkg-config libssl-dev git musl-tools protobuf-compiler libprotobuf-dev
        COPY . ACON
        RUN cd ACON/acond && \
          CARGO_BUILD_RUSTFLAGS=-Ctarget-feature=-crt-static cargo build --release
    - name: Debian builds
      run: docker build --progress=plain -t acond .
